# Generated by Django 5.1.1 on 2025-10-21 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_texttospeechaudio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechToTextAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.CharField(max_length=100, null=True)),
                ('model_version', models.CharField(max_length=100, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lang')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asr_audios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['language'], name='main_speech_languag_acd46d_idx'), models.Index(fields=['user'], name='main_speech_user_id_369687_idx'), models.Index(fields=['created_at'], name='main_speech_created_3f897f_idx'), models.Index(fields=['model_name', 'model_version'], name='main_speech_model_n_9c6108_idx')],
            },
        ),
    ]
