# Generated by Django 5.1.1 on 2025-10-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_generalsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationpair',
            name='is_uncertain',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
