# Generated by Django 5.1.1 on 2025-11-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_translationpair_is_uncertain'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechtotextaudio',
            name='audio_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speechtotextaudio',
            name='audio_format',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
