# Generated by Django 5.1.1 on 2025-11-03 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_speechtotextaudio_audio_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheTTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000)),
                ('audio_data', models.TextField()),
                ('audio_format', models.CharField(default='wav', max_length=10)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lang')),
            ],
            options={
                'indexes': [models.Index(fields=['text', 'language'], name='main_cachet_text_d08f5a_idx')],
                'unique_together': {('text', 'language')},
            },
        ),
    ]
