# Generated by Django 5.1.1 on 2025-11-04 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_cachetts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='speechtotextaudio',
            name='original_text',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='speechtotextaudio',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='speechtotextaudio',
            index=models.Index(fields=['validated'], name='main_speech_validat_9ee979_idx'),
        ),
    ]
