# Generated by Django 5.1.1 on 2025-11-04 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_speechtotextaudio_original_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speechtotextaudio',
            old_name='original_text',
            new_name='validated_text',
        ),
    ]
