# Generated by Django 5.1.1 on 2025-11-04 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_rename_original_text_speechtotextaudio_validated_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_text', models.TextField(max_length=10000)),
                ('dst_text', models.TextField(max_length=10000)),
                ('model_name', models.CharField(max_length=100, null=True)),
                ('model_version', models.CharField(max_length=100, null=True)),
                ('from_cache', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dst_lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dst_translation_requests', to='main.lang')),
                ('src_lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='src_translation_requests', to='main.lang')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['src_lang', 'dst_lang'], name='main_transl_src_lan_4db2dd_idx'), models.Index(fields=['user'], name='main_transl_user_id_9c3b90_idx'), models.Index(fields=['created_at'], name='main_transl_created_fe6294_idx'), models.Index(fields=['from_cache'], name='main_transl_from_ca_0cf48a_idx'), models.Index(fields=['model_name', 'model_version'], name='main_transl_model_n_ee3aa8_idx')],
            },
        ),
    ]
