# Generated by Django 5.1.1 on 2025-11-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_translationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationrequest',
            name='client_request_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
