# Generated by Django 5.1.1 on 2025-11-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_translationrequest_client_request_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speechtotextaudio',
            name='audio_data',
        ),
        migrations.AddField(
            model_name='speechtotextaudio',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='asr_audios/'),
        ),
    ]
