# Generated by Django 5.1.1 on 2026-03-30 00:00

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0052_remove_speechtotextaudio_audio_data_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OCRRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src_languages", models.JSONField(default=list)),
                ("tgt_languages", models.JSONField(default=list)),
                ("provider", models.CharField(default="Gemini", max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="main_ocrreq_created_idx"
                    ),
                    models.Index(fields=["provider"], name="main_ocrreq_provider_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OCRResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uploaded_file",
                    models.FileField(upload_to=main.models.get_ocr_upload_path),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("text", models.TextField(blank=True, null=True)),
                ("pages", models.IntegerField(blank=True, null=True)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ocr_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="main.ocrrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ocr_request"], name="main_ocrres_request_idx"
                    ),
                    models.Index(
                        fields=["original_filename"],
                        name="main_ocrres_filename_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="main_ocrres_created_idx"
                    ),
                ],
            },
        ),
    ]
