# Generated by Django 5.1.1 on 2026-04-20 23:45

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_remove_speechtotextaudio_audio_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speechtotextaudio',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=main.models.get_asr_audio_upload_path),
        ),
    ]
