# Generated by Django 5.1.1 on 2026-04-13 18:01

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_remove_speechtotextaudio_audio_data_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cachetts',
            name='main_cachet_text_d08f5a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='cachetts',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cachetts',
            name='gender',
            field=models.CharField(default='female', max_length=15),
        ),
        migrations.AlterField(
            model_name='speechtotextaudio',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=main.models.get_asr_audio_upload_path),
        ),
        migrations.AlterUniqueTogether(
            name='cachetts',
            unique_together={('text', 'language', 'gender')},
        ),
        migrations.AddIndex(
            model_name='cachetts',
            index=models.Index(fields=['text', 'language', 'gender'], name='main_cachet_text_8d3b3e_idx'),
        ),
    ]
