# Generated by Django 5.1.1 on 2026-03-31 21:33

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_remove_speechtotextaudio_audio_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='speechtotextaudio',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=main.models.get_asr_audio_upload_path),
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.TextField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='main.word')),
            ],
        ),
    ]
