# Generated by Django 5.1.1 on 2026-04-01 21:35

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_ocrrequest_ocrresult'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ocrrequest',
            new_name='main_ocrreq_created_daedd4_idx',
            old_name='main_ocrreq_created_idx',
        ),
        migrations.RenameIndex(
            model_name='ocrrequest',
            new_name='main_ocrreq_provide_05ee11_idx',
            old_name='main_ocrreq_provider_idx',
        ),
        migrations.RenameIndex(
            model_name='ocrresult',
            new_name='main_ocrres_ocr_req_9af6a0_idx',
            old_name='main_ocrres_request_idx',
        ),
        migrations.RenameIndex(
            model_name='ocrresult',
            new_name='main_ocrres_origina_70ad37_idx',
            old_name='main_ocrres_filename_idx',
        ),
        migrations.RenameIndex(
            model_name='ocrresult',
            new_name='main_ocrres_created_8fd0ae_idx',
            old_name='main_ocrres_created_idx',
        ),
        migrations.AlterField(
            model_name='speechtotextaudio',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=main.models.get_asr_audio_upload_path),
        ),
    ]
