# Generated by Django 5.1.1 on 2026-04-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_remove_cachetts_main_cachet_text_d08f5a_idx_and_more'),
        ('main', '0054_wordinformation'),
    ]

    operations = [
    ]
