# Generated by Django 5.1.1 on 2026-04-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_rename_main_ocrreq_created_idx_main_ocrreq_created_daedd4_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrresult',
            name='pages',
        ),
    ]
