# Generated by Django 5.1.1 on 2026-04-21 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_speechtotextaudio_audio_file'),
        ('main', '0055_merge_20260417_1306'),
    ]

    operations = [
    ]
