# Generated by Django 5.1.1 on 2026-04-16 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_remove_ocrresult_pages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ocrrequest',
            index=models.Index(fields=['user'], name='main_ocrreq_user_id_c0a471_idx'),
        ),
    ]
