# Generated by Django 5.1.1 on 2026-04-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_add_user_to_ocr_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrresult',
            name='src_languages',
            field=models.JSONField(default=list),
        ),
    ]
