# Generated by Django 5.1.1 on 2026-09-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_merge_20260421_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='oral_proficiency',
            field=models.CharField(choices=[('Non-Speaker', 'Non-Speaker'), ('Basic', 'Basic'), ('Fluent', 'Fluent')], default='Non-Speaker', max_length=120),
        ),
    ]
