# Generated by Django 5.1.1 on 2026-04-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_ocrresult_src_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrrequest',
            name='corners',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
