# Generated by Django 5.1.1 on 2026-04-23 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_merge_20260421_0001'),
        ('main', '0058_add_corners_to_ocr_request'),
    ]

    operations = [
    ]
